USE hospital3project;

CREATE TABLE IF NOT EXISTS visits (
	visitId INT NOT NULL,
	dateOfVisit DATE NOT NULL,
	patientId INT NOT NULL,
	providerId INT NOT NULL,
	departmentId INT NOT NULL,
	diagnosisId INT NOT NULL,
	procedureId INT NOT NULL,
	insuranceId INT NOT NULL,
	serviceType VARCHAR(50) NOT NULL,
	treatmentCost DECIMAL(6,2) NOT NULL,
	medicationCost DECIMAL(6,2) NOT NULL,
	followUpVisitDate DATE,
	patientSatisfactionScore INT NOT NULL,
	referralSource VARCHAR(50) NOT NULL,
	emergencyVisit VARCHAR(50) NOT NULL,
	paymentStatus VARCHAR(50) NOT NULL,
	dischargeDate DATE,
	admittedDate DATE,
	roomType VARCHAR(50) NOT NULL,
	insuranceCoverage DECIMAL(6,2) NOT NULL, 
	roomCharges DECIMAL(6,2) NOT NULL,
	PRIMARY KEY (visitId)
);


SET GLOBAL local_infile = 1;

LOAD DATA LOCAL INFILE 'C:/Users/billy/OneDrive/Desktop/DataSets/Healthcare Provide Dataset/Healthcare Provide Dataset/visits.csv'
INTO TABLE visits
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

CREATE TABLE IF NOT EXISTS providers (
	providerId INT NOT NULL,
	providerName VARCHAR(50) NOT NULL,
	gender VARCHAR(20) NOT NULL,
	nationality VARCHAR(50) NOT NULL,
	age VARCHAR(50) NOT NULL,
    PRIMARY KEY(providerId)
);

LOAD DATA LOCAL INFILE 'C:/Users/billy/OneDrive/Desktop/DataSets/Healthcare Provide Dataset/Healthcare Provide Dataset/providers.csv'
INTO TABLE providers
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

CREATE TABLE IF NOT EXISTS procedures (
	procedureId INT NOT NULL,
    `procedure` VARCHAR(50) NOT NULL,
    PRIMARY KEY(procedureId)
);

LOAD DATA LOCAL INFILE 'C:/Users/billy/OneDrive/Desktop/DataSets/Healthcare Provide Dataset/Healthcare Provide Dataset/procedures.csv'
INTO TABLE procedures
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

CREATE TABLE IF NOT EXISTS patients (
	patientId INT NOT NULL,
	patientName VARCHAR(50) NOT NULL,
	gender VARCHAR(20) NOT NULL,
	age INT NOT NULL,
	cityId INT NOT NULL,
	race VARCHAR(50) NOT NULL,
	PRIMARY KEY(patientId)
);

LOAD DATA LOCAL INFILE 'C:/Users/billy/OneDrive/Desktop/DataSets/Healthcare Provide Dataset/Healthcare Provide Dataset/patients.csv'
INTO TABLE patients
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

CREATE TABLE IF NOT EXISTS insurance (
	insuranceId INT NOT NULL,
	insuranceProvider VARCHAR(50) NOT NULL,
    PRIMARY KEY(insuranceId)
);

LOAD DATA LOCAL INFILE 'C:/Users/billy/OneDrive/Desktop/DataSets/Healthcare Provide Dataset/Healthcare Provide Dataset/insurance.csv'
INTO TABLE insurance
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

CREATE TABLE IF NOT EXISTS diagnoses (
	diagnosisId INT NOT NULL,
	diagnosis VARCHAR(50) NOT NULL,
	PRIMARY KEY(diagnosisId)
);

LOAD DATA LOCAL INFILE 'C:/Users/billy/OneDrive/Desktop/DataSets/Healthcare Provide Dataset/Healthcare Provide Dataset/diagnoses.csv'
INTO TABLE diagnoses
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

CREATE TABLE IF NOT EXISTS departments (
	departmentId INT NOT NULL,
	department VARCHAR(50) NOT NULL,
	PRIMARY KEY(departmentId)
);

LOAD DATA LOCAL INFILE 'C:/Users/billy/OneDrive/Desktop/DataSets/Healthcare Provide Dataset/Healthcare Provide Dataset/departments.csv'
INTO TABLE departments
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

CREATE TABLE IF NOT EXISTS cities (
	cityId INT NOT NULL,
    city VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL,
    PRIMARY KEY(cityId)
);

LOAD DATA LOCAL INFILE 'C:/Users/billy/OneDrive/Desktop/DataSets/Healthcare Provide Dataset/Healthcare Provide Dataset/cities.csv'
INTO TABLE cities
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- PATIENTS VOLUME AND GROWTH ANALYSIS
-- 1. How many patients visit the hospital each month?
SELECT
	YEAR(dateOfVisit) AS `YEAR`,
    MONTH(dateOfVisit) AS `month`,
    COUNT(*) AS patientCount
FROM visits
GROUP BY YEAR(dateOfVisit), MONTH(dateOfVisit)
ORDER BY YEAR(dateOfVisit), MONTH(dateOfVisit);

-- 2. Which departments receive the most patient visits?
SELECT 
	v.departmentId,
    d.department,
    COUNT(visitId) AS totalPatientCount
FROM visits v
JOIN departments d
	ON v.departmentId	= d.departmentId
GROUP BY
	v.departmentId,
    d.department
ORDER BY v.departmentId;

-- 3. Which cities generate the most patients?
SELECT
    c.city,
    COUNT(patientId) AS totalPatientCount
FROM patients p
JOIN cities c
	ON p.cityId	= c.cityId
GROUP BY 
    c.city
ORDER BY totalPatientCount DESC;

-- REVENUE AND FINANCIAL PERFORMANCE
-- 4. What is the total revenue generated by each department?
SELECT
	department,
    SUM(COALESCE(v.treatmentcost, 0) + COALESCE(v.medicationCost, 0)) AS totalCosts
FROM visits v
JOIN departments d
	ON v.departmentid = d.departmentId
GROUP BY department
ORDER BY totalCosts DESC;

-- 5. Which procedures generate the highest revenue?
SELECT
    p.procedure,
    SUM(COALESCE(v.treatmentcost, 0) + COALESCE(v.medicationCost, 0)) AS totalCosts
FROM visits v
JOIN procedures p
    ON v.procedureId = p.procedureId 
GROUP BY p.procedure;

-- 6. What percentage of revenue is covered by insurance?
SELECT
    ROUND(
        SUM(insuranceCoverage) /SUM(treatmentCost + medicationCost + roomCharges) * 100,2) AS insuranceCoveragePercentage
FROM visits;

-- 7. Which insurance providers contribute the most revenue?
SELECT
	v.insuranceId,
    SUM(treatmentCost + medicationCost + roomCharges) AS totalRevenue
FROM visits v
JOIN insurance i
	ON 	v.insuranceId = i.insuranceId
GROUP BY v.insuranceId
ORDER BY totalRevenue DESC;


-- PATIENT SATISFACTION ANALYSIS
-- 8. Which departments have the highest patient satisfaction scores?
SELECT
	v.departmentId,
	d.department,
    AVG(patientSatisfactionScore) AS AVGSatisfactionScore
FROM visits v
JOIN departments d
	ON v.departmentId = d.departmentId
GROUP BY
	v.departmentId,
	d.department
ORDER BY AVGSatisfactionScore DESC;

-- 9. Which providers receive the highest patient satisfaction scores?
SELECT
	v.providerId,
	p.providerName,
    AVG(patientSatisfactionScore) AS AVGSatisfactionScore
FROM visits v
JOIN providers p
	ON p.providerId = v.providerId
GROUP BY
	v.providerId,
	p.providerName
ORDER BY AVGSatisfactionScore DESC;


-- 10. Does treatment cost affect patient satisfaction?
SELECT
    CASE
        WHEN treatmentCost < 500 THEN 'Low Cost'
        WHEN treatmentCost BETWEEN 500 AND 999.99 THEN 'Medium Cost'
        ELSE 'High Cost'
    END AS costCategory,
    COUNT(*) AS totalVisits,
    ROUND(AVG(patientSatisfactionScore), 2) AS avgSatisfactionScore
FROM visits
GROUP BY costCategory
ORDER BY avgSatisfactionScore DESC;

-- PROVIDER PERFORMANCE ANALYSIS
-- 11. Which providers handle the most patients?
SELECT
	v.providerId,
	p.providerName,
    COUNT(visitId) AS totalPatientCount
FROM visits v
JOIN providers p
	ON p.providerId = v.providerId
GROUP BY
	v.providerId,
	p.providerName
ORDER BY totalPatientCount DESC;

-- 12. Which providers generate the highest revenue?
SELECT
	v.providerId,
	p.providerName,
    SUM(COALESCE(v.treatmentcost, 0) + COALESCE(v.medicationCost, 0)) AS totalRevenue
FROM visits v
JOIN providers p
	ON p.providerId = v.providerId
GROUP BY
	v.providerId,
	p.providerName
ORDER BY totalRevenue DESC;

-- DIAGNOSIS AND DISEASE ANALYSIS
-- 13. What are the most common diagnoses?
SELECT
	v.diagnosisId,
    d.diagnosis,
    COUNT(visitId) AS totalPatientCount
FROM visits v
JOIN diagnoses d
	ON v.diagnosisId = d.diagnosisId
GROUP BY
	v.diagnosisId,
    d.diagnosis
ORDER BY 
	totalPatientCount DESC;

-- 14. Which diagnoses generate the highest treatment costs?
SELECT
	v.diagnosisId,
    d.diagnosis,
        SUM(COALESCE(v.treatmentcost, 0) + COALESCE(v.medicationCost, 0)) AS totalCosts
FROM visits v
JOIN diagnoses d
	ON v.diagnosisId = d.diagnosisId
GROUP BY
	v.diagnosisId,
    d.diagnosis
ORDER BY 
	totalCosts DESC;
    
-- EMERGENCY SERVICE ANALYSIS
-- 15. What percentage of visits are emergency visits?
SELECT
    ROUND(
        SUM(CASE WHEN referralSource = 'Emergency' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2 ) AS percentageEmergencyVisit
FROM visits;

-- 16. Which diagnoses most frequently result in emergency visits?
SELECT
	v.diagnosisId,
    d.diagnosis,
    SUM(CASE WHEN referralSource = 'Emergency' THEN 1 ELSE 0 END) AS totalEmergencyCount
FROM visits v
JOIN diagnoses d
	ON v.diagnosisId = d.diagnosisId
GROUP BY
	v.diagnosisId,
    d.diagnosis
ORDER BY
	totalEmergencyCount DESC;

-- INSURANCE ANALYSIS
-- 17. Which insurance providers cover the most patients?
SELECT
	v.insuranceId,
    i.insuranceProvider,
    COUNT(visitId) AS totalCount
FROM visits v
JOIN insurance i
	ON v.insuranceId = i.insuranceId
GROUP BY
	v.insuranceId,
    i.insuranceProvider
ORDER BY totalCount;

-- 18. Which insurance providers have the highest unpaid claims?
SELECT
    v.insuranceId,
    i.insuranceProvider,
    SUM(COALESCE(v.insuranceCoverage, 0)) AS unpaidClaims
FROM visits v
JOIN insurance i
    ON v.insuranceId = i.insuranceId
WHERE v.paymentStatus = 'Pending' 
GROUP BY
    v.insuranceId,
    i.insuranceProvider
ORDER BY unpaidClaims DESC; 

-- 19. Which referral sources generate the most patients?
SELECT
    referralSource,
    COUNT(DISTINCT patientId) AS totalPatients,
    ROUND(COUNT(DISTINCT patientId) * 100.0 /
        (SELECT COUNT(DISTINCT patientId)
            FROM visits),2) AS patientPercentage
FROM visits
GROUP BY referralSource
ORDER BY totalPatients DESC;

-- 20. Which referral sources generate the highest revenue?
SELECT
    referralSource,
    SUM(treatmentCost + medicationCost + roomCharges) AS totalRevenue
FROM visits
GROUP BY referralSource
ORDER BY totalRevenue DESC;

-- 21. Which age groups generate the highest healthcare spending?
SELECT
    CASE
        WHEN p.age BETWEEN 0 AND 17 THEN 'Children (0-17)'
        WHEN p.age BETWEEN 18 AND 35 THEN 'Young Adults (18-35)'
        WHEN p.age BETWEEN 36 AND 55 THEN 'Middle-Aged (36-55)'
        WHEN p.age BETWEEN 56 AND 75 THEN 'Seniors (56-75)'
        ELSE 'Elderly (76+)'
    END AS ageGroup,
    COUNT(DISTINCT v.patientId) AS total_patients,
    ROUND(SUM(v.treatmentCost + v.medicationCost + v.roomCharges),2) AS totalHealthcareSpending,
    ROUND(AVG(v.treatmentCost + v.medicationCost + v.roomCharges),2) AS avgSpendingPerVisit
FROM visits v
JOIN patients p
    ON v.patientId = p.patientId
GROUP BY ageGroup
ORDER BY totalHealthcareSpending DESC;

-- 22. Which gender has the highest average treatment cost?
SELECT
	gender,
    AVG    (treatmentCost + medicationCost + roomCharges) AS avgtotalCost
FROM visits v
JOIN patients p
	ON v.patientId = p.patientId
GROUP BY gender
ORDER BY avgtotalCost DESC;

-- 23. What percentage of visits have unpaid balances?
SELECT
    COUNT(*) AS totalVisits,
    COUNT(CASE WHEN LOWER(paymentStatus) IN ('unpaid','pending','partially paid')
            THEN 1 END) AS unpaidVisits,
    ROUND(COUNT(CASE WHEN LOWER(paymentStatus) IN ('unpaid','pending','partially paid')
			THEN 1 END) * 100.0 / COUNT(*),2) AS unpaidBalancePercentage
FROM visits;

-- 24. Which diagnoses have high costs but low patient satisfaction?
SELECT
    dep.department,
    d.diagnosis,
    ROUND(AVG(v.treatmentCost + v.medicationCost + v.roomCharges),2) AS avgCost,
    ROUND(AVG(v.patientSatisfactionScore),2) AS avgSatisfaction
FROM visits v
JOIN diagnoses d
    ON v.diagnosisId = d.diagnosisId
JOIN departments dep
    ON v.departmentId = dep.departmentId
GROUP BY
    dep.department,
    d.diagnosis
ORDER BY avgCost DESC;

-- 25. Which departments have both high patient volume and low satisfaction?
SELECT
    d.department,
    COUNT(v.visitId) AS total_visits,
    ROUND(AVG(v.patientSatisfactionScore),2) AS avgSatisfaction
FROM visits v
JOIN departments d
    ON v.departmentId = d.departmentId
GROUP BY d.department
HAVING
    COUNT(v.visitId) >
    (SELECT AVG(dept_visits)
	FROM (
            SELECT COUNT(*) AS dept_visits
            FROM visits
            GROUP BY departmentId) x    )
AND AVG(v.patientSatisfactionScore)< (SELECT AVG(patientSatisfactionScore)
        FROM visits)
ORDER BY total_visits DESC;


